# Generated by Django 4.2.7 on 2023-12-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DayCare', '0006_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
