# Generated by Django 4.2.8 on 2023-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayCare', '0007_parent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hospitals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='schools',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
