# Generated by Django 4.2.7 on 2023-11-21 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DayCare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'First name should be more than two characters')])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Last name should be more than two characters')])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(18, 'Maximum child age should be 18!')])),
                ('has_special_needs', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(choices=[('Borovo', 'Borovo'), ('Belite Brezi', 'Belite Brezi'), ('Strelbishte', 'Strelbishte'), ('Manastirski Livadi', 'Manastirski Livadi'), ('Luilin 1', 'Luilin 1'), ('Luilin 2', 'Luilin 2'), ('Luilin 3', 'Luilin 3'), ('Luilin 4', 'Luilin 4'), ('Luilin 5', 'Luilin 5'), ('Luilin 6', 'Luilin 6'), ('Luilin 7', 'Luilin 7'), ('Luilin 8', 'Luilin 8'), ('Luilin 9', 'Luilin 9'), ('Mladost 1', 'Mladost 1'), ('Mladost 2', 'Mladost 2'), ('Mladost 3', 'Mladost 3'), ('Mladost 4', 'Mladost 4'), ('Nadejda 1', 'Nadejda 1'), ('Nadejda 2', 'Nadejda 2'), ('Ovcha kupel 1', 'Ovcha kupel 1'), ('Ovcha kupel 2', 'Ovcha kupel 2')])),
                ('hospitals', models.BooleanField()),
                ('schools', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DayCare.location')),
                ('min_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0, 'Rating cannot be less than 0!'), django.core.validators.MaxValueValidator(10, 'Rating cannot be more than 10!')])),
                ('price_per_hour', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0, 'Price cannot be less than 0!'), django.core.validators.MaxValueValidator(900, 'Price cannot be more than 900!')])),
            ],
            bases=('DayCare.location', models.Model),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'First name should be more than two characters')])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Last name should be more than two characters')])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, 'Parent cannot be younger than 18!'), django.core.validators.MaxValueValidator(100, 'Are you a vampire? Maximum age should be 100 years old!')])),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0, 'Rating cannot be less than 0!'), django.core.validators.MaxValueValidator(10, 'Rating cannot be more than 10!')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('parent_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayCare.child')),
                ('parent_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DayCare.offers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
