# Generated by Django 4.2.7 on 2023-11-28 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DayCare', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DayCare.child'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DayCare.offers'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0, 'Rating cannot be less than 0!'), django.core.validators.MaxValueValidator(10, 'Rating cannot be more than 10!')]),
        ),
    ]
