# Generated by Django 4.2.7 on 2023-12-01 08:33

import DayCareApp.DayCare.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayCare', '0003_alter_parent_parent_child_alter_parent_parent_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, 'Parent cannot be younger than 18!'), django.core.validators.MaxValueValidator(100, 'Maximum age should be 100 years old!')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=30, validators=[DayCareApp.DayCare.validators.password_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
