# Generated by Django 4.2.8 on 2023-12-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DayCare', '0008_alter_location_hospitals_alter_location_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hospitals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='schools',
            field=models.BooleanField(default=False),
        ),
    ]
